[package]
name = "verus-test"
version = "0.1.0"
edition = "2021"

[dependencies]
vstd = { git = "https://github.com/verus-lang/verus.git" }
state_machines_macros = { git = "https://github.com/verus-lang/verus.git" }